// lib/optimizer/platform-config.ts
import { PlatformSpec, MonetizationOption, GrowthStrategy } from "@/types/optimizer";

export const PLATFORM_SPECS: Record<string, PlatformSpec> = {
  instagram: {
    name: "instagram",
    displayName: "Instagram",
    icon: "📸",
    color: "#E4405F",
    bioMaxLength: 150,
    headlineMaxLength: 30,
    linkAllowed: true,
    linkLimit: 1,
    bestPostingTimes: ["9:00 AM", "1:00 PM", "7:00 PM"],
    contentTypes: ["Reels", "Posts", "Stories", "Carousels", "Live"],
    audienceType: "Visual, lifestyle, 18-34 age group",
    toneRecommendation: "Authentic, engaging, visually appealing",
    monetizationOptions: [
      {
        id: "ig-brand-deals",
        name: "Brand Partnerships",
        description: "Partner with brands for sponsored posts",
        eligibility: "1K+ followers, good engagement",
        earningPotential: "$100-$10,000+ per post",
        difficulty: "medium",
        timeToRevenue: "2-6 months",
      },
      {
        id: "ig-affiliate",
        name: "Affiliate Marketing",
        description: "Earn commission on product recommendations",
        eligibility: "Any follower count",
        earningPotential: "$50-$5,000/month",
        difficulty: "easy",
        timeToRevenue: "1-3 months",
      },
      {
        id: "ig-products",
        name: "Instagram Shopping",
        description: "Sell products directly through Instagram",
        eligibility: "Business account, compliant products",
        earningPotential: "Varies by product",
        difficulty: "medium",
        timeToRevenue: "1-2 months",
      },
      {
        id: "ig-badges",
        name: "Live Badges",
        description: "Earn from viewers during Live videos",
        eligibility: "10K+ followers",
        earningPotential: "$100-$1,000/month",
        difficulty: "medium",
        timeToRevenue: "3-6 months",
      },
      {
        id: "ig-subscriptions",
        name: "Subscriptions",
        description: "Monthly subscription for exclusive content",
        eligibility: "10K+ followers, 18+",
        earningPotential: "$500-$10,000/month",
        difficulty: "hard",
        timeToRevenue: "4-8 months",
      },
    ],
    growthStrategies: [
      {
        id: "ig-reels",
        name: "Post Reels Daily",
        description: "Reels get 3x more reach than regular posts",
        effort: "medium",
        impact: "high",
        timeToResult: "2-4 weeks",
      },
      {
        id: "ig-engagement",
        name: "Engage 30 min/day",
        description: "Comment on niche accounts in your industry",
        effort: "low",
        impact: "high",
        timeToResult: "1-2 weeks",
      },
      {
        id: "ig-collabs",
        name: "Collaborate with Creators",
        description: "Collab posts expose you to new audiences",
        effort: "medium",
        impact: "high",
        timeToResult: "2-4 weeks",
      },
      {
        id: "ig-hashtags",
        name: "Use 10-15 Relevant Hashtags",
        description: "Mix of small, medium, and large hashtags",
        effort: "low",
        impact: "medium",
        timeToResult: "1-2 weeks",
      },
      {
        id: "ig-stories",
        name: "Post 5-10 Stories Daily",
        description: "Stories keep you top-of-mind with followers",
        effort: "medium",
        impact: "medium",
        timeToResult: "2-3 weeks",
      },
    ],
  },

  linkedin: {
    name: "linkedin",
    displayName: "LinkedIn",
    icon: "💼",
    color: "#0A66C2",
    bioMaxLength: 2600,
    headlineMaxLength: 220,
    linkAllowed: true,
    linkLimit: 5,
    bestPostingTimes: ["8:00 AM", "12:00 PM", "5:00 PM"],
    contentTypes: ["Posts", "Articles", "Videos", "Documents", "Polls", "Newsletter"],
    audienceType: "Professionals, B2B, 25-54 age group",
    toneRecommendation: "Professional, value-driven, informative",
    monetizationOptions: [
      {
        id: "li-consulting",
        name: "Consulting Services",
        description: "Offer consulting through LinkedIn",
        eligibility: "Strong profile, expertise",
        earningPotential: "$1,000-$50,000+/month",
        difficulty: "medium",
        timeToRevenue: "2-6 months",
      },
      {
        id: "li-courses",
        name: "Online Courses",
        description: "Create and sell courses to your network",
        eligibility: "Expertise in niche",
        earningPotential: "$500-$20,000/month",
        difficulty: "medium",
        timeToRevenue: "3-6 months",
      },
      {
        id: "li-newsletter",
        name: "LinkedIn Newsletter",
        description: "Build audience, monetize through sponsors",
        eligibility: "Any follower count",
        earningPotential: "$500-$10,000/month",
        difficulty: "medium",
        timeToRevenue: "4-8 months",
      },
      {
        id: "li-coaching",
        name: "1-on-1 Coaching",
        description: "Offer personalized coaching services",
        eligibility: "Proven expertise",
        earningPotential: "$100-$500/hour",
        difficulty: "medium",
        timeToRevenue: "1-3 months",
      },
      {
        id: "li-speaker",
        name: "Speaking Engagements",
        description: "Get booked for events and webinars",
        eligibility: "Strong personal brand",
        earningPotential: "$1,000-$20,000/speech",
        difficulty: "hard",
        timeToRevenue: "6-12 months",
      },
    ],
    growthStrategies: [
      {
        id: "li-content",
        name: "Post 3-5x Weekly",
        description: "Consistent posting builds authority",
        effort: "medium",
        impact: "high",
        timeToResult: "4-8 weeks",
      },
      {
        id: "li-commenting",
        name: "Comment on Top Voices",
        description: "Comment on industry leaders' posts daily",
        effort: "low",
        impact: "high",
        timeToResult: "2-4 weeks",
      },
      {
        id: "li-connections",
        name: "Send 20 Connection Requests/Day",
        description: "Personalized requests to target audience",
        effort: "medium",
        impact: "medium",
        timeToResult: "2-4 weeks",
      },
      {
        id: "li-newsletter",
        name: "Start a Newsletter",
        description: "Weekly newsletter builds loyal audience",
        effort: "high",
        impact: "high",
        timeToResult: "8-12 weeks",
      },
      {
        id: "li-profile",
        name: "Optimize Profile for SEO",
        description: "Keywords in headline, about, experience",
        effort: "low",
        impact: "high",
        timeToResult: "1-2 weeks",
      },
    ],
  },

  twitter: {
    name: "twitter",
    displayName: "Twitter/X",
    icon: "🐦",
    color: "#1DA1F2",
    bioMaxLength: 160,
    headlineMaxLength: 50,
    linkAllowed: true,
    linkLimit: 1,
    bestPostingTimes: ["8:00 AM", "12:00 PM", "6:00 PM"],
    contentTypes: ["Tweets", "Threads", "Spaces", "Videos", "Polls"],
    audienceType: "News-focused, real-time, 18-49 age group",
    toneRecommendation: "Concise, timely, engaging, authentic",
    monetizationOptions: [
      {
        id: "tw-ads-revenue",
        name: "Ads Revenue Sharing",
        description: "Earn from ads in your replies",
        eligibility: "500+ followers, 5M impressions/3 months",
        earningPotential: "$100-$10,000/month",
        difficulty: "medium",
        timeToRevenue: "3-6 months",
      },
      {
        id: "tw-subscriptions",
        name: "Twitter Subscriptions",
        description: "Monthly subscription for exclusive content",
        eligibility: "500+ followers, 18+",
        earningPotential: "$500-$20,000/month",
        difficulty: "medium",
        timeToRevenue: "2-4 months",
      },
      {
        id: "tw-affiliate",
        name: "Affiliate Links",
        description: "Share affiliate links in tweets",
        eligibility: "Any follower count",
        earningPotential: "$100-$5,000/month",
        difficulty: "easy",
        timeToRevenue: "1-3 months",
      },
      {
        id: "tw-sponsorships",
        name: "Sponsored Tweets",
        description: "Brands pay for promotional tweets",
        eligibility: "5K+ followers, good engagement",
        earningPotential: "$200-$10,000/tweet",
        difficulty: "medium",
        timeToRevenue: "3-6 months",
      },
      {
        id: "tw-coaching",
        name: "Twitter Coaching",
        description: "Teach others to grow on Twitter",
        eligibility: "Proven growth results",
        earningPotential: "$500-$10,000/month",
        difficulty: "medium",
        timeToRevenue: "2-4 months",
      },
    ],
    growthStrategies: [
      {
        id: "tw-threads",
        name: "Write Viral Threads",
        description: "Threads get 10x more reach than single tweets",
        effort: "high",
        impact: "high",
        timeToResult: "4-8 weeks",
      },
      {
        id: "tw-engagement",
        name: "Reply to Big Accounts",
        description: "Early replies to viral tweets get visibility",
        effort: "low",
        impact: "high",
        timeToResult: "1-2 weeks",
      },
      {
        id: "tw-consistency",
        name: "Tweet 5-10x Daily",
        description: "Consistency builds algorithmic favor",
        effort: "high",
        impact: "high",
        timeToResult: "4-8 weeks",
      },
      {
        id: "tw-spaces",
        name: "Host Twitter Spaces",
        description: "Audio rooms build community",
        effort: "medium",
        impact: "medium",
        timeToResult: "4-6 weeks",
      },
      {
        id: "tw-niche",
        name: "Own a Niche Topic",
        description: "Become the go-to account for specific topic",
        effort: "medium",
        impact: "high",
        timeToResult: "8-12 weeks",
      },
    ],
  },

  tiktok: {
    name: "tiktok",
    displayName: "TikTok",
    icon: "🎵",
    color: "#000000",
    bioMaxLength: 80,
    headlineMaxLength: 30,
    linkAllowed: true,
    linkLimit: 1,
    bestPostingTimes: ["6:00 AM", "10:00 AM", "10:00 PM"],
    contentTypes: ["Short Videos", "Live", "Photo Posts", "Stories"],
    audienceType: "Gen Z, Millennials, 16-34 age group",
    toneRecommendation: "Entertaining, authentic, trending",
    monetizationOptions: [
      {
        id: "tt-creator-fund",
        name: "Creator Fund",
        description: "Earn from video views",
        eligibility: "10K+ followers, 100K views/30 days",
        earningPotential: "$50-$2,000/month",
        difficulty: "medium",
        timeToRevenue: "3-6 months",
      },
      {
        id: "tt-brand-deals",
        name: "Brand Partnerships",
        description: "Sponsored content with brands",
        eligibility: "10K+ followers",
        earningPotential: "$200-$50,000/video",
        difficulty: "medium",
        timeToRevenue: "3-6 months",
      },
      {
        id: "tt-live-gifts",
        name: "Live Gifts",
        description: "Viewers send virtual gifts during Lives",
        eligibility: "1K+ followers, 18+",
        earningPotential: "$100-$10,000/month",
        difficulty: "easy",
        timeToRevenue: "2-4 months",
      },
      {
        id: "tt-series",
        name: "TikTok Series",
        description: "Premium content behind paywall",
        eligibility: "10K+ followers, 18+",
        earningPotential: "$500-$20,000/month",
        difficulty: "medium",
        timeToRevenue: "4-6 months",
      },
      {
        id: "tt-affiliate",
        name: "TikTok Shop Affiliate",
        description: "Earn commission on products",
        eligibility: "5K+ followers, 18+",
        earningPotential: "$500-$50,000/month",
        difficulty: "easy",
        timeToRevenue: "1-3 months",
      },
    ],
    growthStrategies: [
      {
        id: "tt-trending",
        name: "Use Trending Sounds",
        description: "Trending audio gets algorithmic boost",
        effort: "low",
        impact: "high",
        timeToResult: "1-2 weeks",
      },
      {
        id: "tt-hook",
        name: "3-Second Hook",
        description: "Grab attention in first 3 seconds",
        effort: "medium",
        impact: "high",
        timeToResult: "1-2 weeks",
      },
      {
        id: "tt-frequency",
        name: "Post 1-3x Daily",
        description: "Frequency builds momentum",
        effort: "high",
        impact: "high",
        timeToResult: "4-8 weeks",
      },
      {
        id: "tt-duets",
        name: "Duets & Stitches",
        description: "Leverage existing viral content",
        effort: "low",
        impact: "medium",
        timeToResult: "2-4 weeks",
      },
      {
        id: "tt-series",
        name: "Create Content Series",
        description: "Episodic content keeps viewers coming back",
        effort: "medium",
        impact: "high",
        timeToResult: "4-8 weeks",
      },
    ],
  },

  youtube: {
    name: "youtube",
    displayName: "YouTube",
    icon: "📺",
    color: "#FF0000",
    bioMaxLength: 1000,
    headlineMaxLength: 100,
    linkAllowed: true,
    linkLimit: 5,
    bestPostingTimes: ["2:00 PM", "4:00 PM", "6:00 PM"],
    contentTypes: ["Long-form Videos", "Shorts", "Live", "Community Posts", "Stories"],
    audienceType: "All ages, search-driven, 18-54 age group",
    toneRecommendation: "Educational, entertaining, valuable",
    monetizationOptions: [
      {
        id: "yt-adsense",
        name: "AdSense Revenue",
        description: "Earn from ads on your videos",
        eligibility: "1K subscribers, 4K watch hours",
        earningPotential: "$500-$100,000+/month",
        difficulty: "medium",
        timeToRevenue: "6-12 months",
      },
      {
        id: "yt-memberships",
        name: "Channel Memberships",
        description: "Monthly membership for exclusive perks",
        eligibility: "30K+ subscribers",
        earningPotential: "$1,000-$50,000/month",
        difficulty: "medium",
        timeToRevenue: "8-12 months",
      },
      {
        id: "yt-sponsorships",
        name: "Video Sponsorships",
        description: "Brands sponsor your videos",
        eligibility: "10K+ subscribers",
        earningPotential: "$500-$100,000/video",
        difficulty: "medium",
        timeToRevenue: "6-12 months",
      },
      {
        id: "yt-affiliate",
        name: "Affiliate Links",
        description: "Commission from product recommendations",
        eligibility: "Any subscriber count",
        earningPotential: "$200-$20,000/month",
        difficulty: "easy",
        timeToRevenue: "3-6 months",
      },
      {
        id: "yt-merch",
        name: "Merchandise Shelf",
        description: "Sell branded merchandise",
        eligibility: "10K+ subscribers",
        earningPotential: "$500-$50,000/month",
        difficulty: "medium",
        timeToRevenue: "6-12 months",
      },
    ],
    growthStrategies: [
      {
        id: "yt-seo",
        name: "Optimize for Search",
        description: "Keywords in title, description, tags",
        effort: "medium",
        impact: "high",
        timeToResult: "4-8 weeks",
      },
      {
        id: "yt-thumbnails",
        name: "Create Click-Worthy Thumbnails",
        description: "Thumbnails determine 90% of clicks",
        effort: "medium",
        impact: "high",
        timeToResult: "2-4 weeks",
      },
      {
        id: "yt-shorts",
        name: "Post YouTube Shorts",
        description: "Shorts get massive reach for new channels",
        effort: "low",
        impact: "high",
        timeToResult: "2-4 weeks",
      },
      {
        id: "yt-consistency",
        name: "Upload Schedule",
        description: "Consistent uploads build audience habits",
        effort: "high",
        impact: "high",
        timeToResult: "8-12 weeks",
      },
      {
        id: "yt-engagement",
        name: "Reply to All Comments",
        description: "Engagement boosts algorithmic favor",
        effort: "medium",
        impact: "medium",
        timeToResult: "4-8 weeks",
      },
    ],
  },

  facebook: {
    name: "facebook",
    displayName: "Facebook",
    icon: "📘",
    color: "#1877F2",
    bioMaxLength: 255,
    headlineMaxLength: 100,
    linkAllowed: true,
    linkLimit: 10,
    bestPostingTimes: ["1:00 PM", "3:00 PM", "4:00 PM"],
    contentTypes: ["Posts", "Videos", "Reels", "Live", "Stories", "Groups"],
    audienceType: "All ages, community-focused, 25-65 age group",
    toneRecommendation: "Friendly, community-oriented, shareable",
    monetizationOptions: [
      {
        id: "fb-instream-ads",
        name: "In-Stream Ads",
        description: "Ads in your videos",
        eligibility: "10K+ followers, 600K minutes viewed",
        earningPotential: "$200-$20,000/month",
        difficulty: "medium",
        timeToRevenue: "6-12 months",
      },
      {
        id: "fb-stars",
        name: "Facebook Stars",
        description: "Viewers send stars during Lives",
        eligibility: "500+ followers, 18+",
        earningPotential: "$100-$10,000/month",
        difficulty: "easy",
        timeToRevenue: "3-6 months",
      },
      {
        id: "fb-subscriptions",
        name: "Page Subscriptions",
        description: "Monthly subscription for exclusive content",
        eligibility: "10K+ followers",
        earningPotential: "$500-$20,000/month",
        difficulty: "medium",
        timeToRevenue: "4-8 months",
      },
      {
        id: "fb-brand-collabs",
        name: "Brand Collaborations",
        description: "Sponsored content with brands",
        eligibility: "5K+ followers",
        earningPotential: "$200-$20,000/post",
        difficulty: "medium",
        timeToRevenue: "4-8 months",
      },
      {
        id: "fb-shop",
        name: "Facebook Shop",
        description: "Sell products directly on Facebook",
        eligibility: "Business account",
        earningPotential: "Varies by product",
        difficulty: "easy",
        timeToRevenue: "1-3 months",
      },
    ],
    growthStrategies: [
      {
        id: "fb-groups",
        name: "Create/Join Groups",
        description: "Groups have higher engagement than pages",
        effort: "medium",
        impact: "high",
        timeToResult: "4-8 weeks",
      },
      {
        id: "fb-reels",
        name: "Post Facebook Reels",
        description: "Reels get priority in algorithm",
        effort: "medium",
        impact: "high",
        timeToResult: "2-4 weeks",
      },
      {
        id: "fb-live",
        name: "Go Live Weekly",
        description: "Live videos get 6x more engagement",
        effort: "medium",
        impact: "medium",
        timeToResult: "4-8 weeks",
      },
      {
        id: "fb-sharing",
        name: "Create Shareable Content",
        description: "Shares exponentially increase reach",
        effort: "medium",
        impact: "high",
        timeToResult: "4-8 weeks",
      },
      {
        id: "fb-ads",
        name: "Run Page Like Ads",
        description: "Low-cost ads to build initial audience",
        effort: "low",
        impact: "medium",
        timeToResult: "2-4 weeks",
      },
    ],
  },

  pinterest: {
    name: "pinterest",
    displayName: "Pinterest",
    icon: "📌",
    color: "#E60023",
    bioMaxLength: 160,
    headlineMaxLength: 100,
    linkAllowed: true,
    linkLimit: 1,
    bestPostingTimes: ["8:00 PM", "9:00 PM"],
    contentTypes: ["Pins", "Idea Pins", "Videos", "Boards"],
    audienceType: "Visual planners, DIY, lifestyle, 25-54 age group",
    toneRecommendation: "Inspirational, helpful, visual",
    monetizationOptions: [
      {
        id: "pi-affiliate",
        name: "Affiliate Marketing",
        description: "Affiliate links in pins",
        eligibility: "Any follower count",
        earningPotential: "$200-$20,000/month",
        difficulty: "easy",
        timeToRevenue: "2-4 months",
      },
      {
        id: "pi-sponsored",
        name: "Sponsored Pins",
        description: "Brands pay for promoted pins",
        eligibility: "5K+ monthly viewers",
        earningPotential: "$500-$10,000/month",
        difficulty: "medium",
        timeToRevenue: "4-8 months",
      },
      {
        id: "pi-products",
        name: "Sell Products",
        description: "Drive traffic to your online store",
        eligibility: "Business account",
        earningPotential: "$500-$50,000/month",
        difficulty: "medium",
        timeToRevenue: "3-6 months",
      },
      {
        id: "pi-consulting",
        name: "Pinterest Consulting",
        description: "Help businesses grow on Pinterest",
        eligibility: "Proven results",
        earningPotential: "$1,000-$10,000/month",
        difficulty: "medium",
        timeToRevenue: "3-6 months",
      },
      {
        id: "pi-courses",
        name: "Pinterest Courses",
        description: "Teach Pinterest marketing",
        eligibility: "Expertise in Pinterest",
        earningPotential: "$1,000-$50,000/month",
        difficulty: "hard",
        timeToRevenue: "6-12 months",
      },
    ],
    growthStrategies: [
      {
        id: "pi-seo",
        name: "Optimize Pins for Search",
        description: "Keywords in title, description, alt text",
        effort: "medium",
        impact: "high",
        timeToResult: "4-8 weeks",
      },
      {
        id: "pi-consistency",
        name: "Pin 10-20x Daily",
        description: "Consistency is key on Pinterest",
        effort: "high",
        impact: "high",
        timeToResult: "8-12 weeks",
      },
      {
        id: "pi-boards",
        name: "Create Niche Boards",
        description: "Organized boards improve discoverability",
        effort: "low",
        impact: "medium",
        timeToResult: "4-8 weeks",
      },
      {
        id: "pi-idea-pins",
        name: "Create Idea Pins",
        description: "Idea Pins get priority in algorithm",
        effort: "medium",
        impact: "high",
        timeToResult: "4-8 weeks",
      },
      {
        id: "pi-rich-pins",
        name: "Enable Rich Pins",
        description: "Rich pins show more information",
        effort: "low",
        impact: "medium",
        timeToResult: "2-4 weeks",
      },
    ],
  },

  medium: {
    name: "medium",
    displayName: "Medium",
    icon: "📝",
    color: "#000000",
    bioMaxLength: 160,
    headlineMaxLength: 100,
    linkAllowed: true,
    linkLimit: 10,
    bestPostingTimes: ["7:00 AM", "12:00 PM", "6:00 PM"],
    contentTypes: ["Articles", "Publications", "Newsletters"],
    audienceType: "Readers, thought leaders, professionals",
    toneRecommendation: "In-depth, thoughtful, well-researched",
    monetizationOptions: [
      {
        id: "md-partner",
        name: "Partner Program",
        description: "Earn from member reading time",
        eligibility: "3 published stories, 18+",
        earningPotential: "$100-$10,000/month",
        difficulty: "medium",
        timeToRevenue: "3-6 months",
      },
      {
        id: "md-tipping",
        name: "Member Tipping",
        description: "Readers can tip you directly",
        eligibility: "Partner Program member",
        earningPotential: "$50-$2,000/month",
        difficulty: "easy",
        timeToRevenue: "3-6 months",
      },
      {
        id: "md-newsletter",
        name: "Paid Newsletter",
        description: "Subscription-based newsletter",
        eligibility: "Established audience",
        earningPotential: "$500-$20,000/month",
        difficulty: "medium",
        timeToRevenue: "6-12 months",
      },
      {
        id: "md-consulting",
        name: "Consulting Services",
        description: "Offer consulting through articles",
        eligibility: "Expertise in niche",
        earningPotential: "$1,000-$20,000/month",
        difficulty: "medium",
        timeToRevenue: "4-8 months",
      },
      {
        id: "md-courses",
        name: "Online Courses",
        description: "Create courses based on articles",
        eligibility: "Established expertise",
        earningPotential: "$1,000-$50,000/month",
        difficulty: "hard",
        timeToRevenue: "6-12 months",
      },
    ],
    growthStrategies: [
      {
        id: "md-publications",
        name: "Write for Publications",
        description: "Publications have built-in audiences",
        effort: "medium",
        impact: "high",
        timeToResult: "4-8 weeks",
      },
      {
        id: "md-consistency",
        name: "Publish 2-4x Weekly",
        description: "Consistency builds readership",
        effort: "high",
        impact: "high",
        timeToResult: "8-12 weeks",
      },
      {
        id: "md-networking",
        name: "Engage with Other Writers",
        description: "Clap, comment, build relationships",
        effort: "low",
        impact: "medium",
        timeToResult: "4-8 weeks",
      },
      {
        id: "md-seo",
        name: "Optimize for SEO",
        description: "Keywords in title, subtitle, tags",
        effort: "medium",
        impact: "high",
        timeToResult: "8-12 weeks",
      },
      {
        id: "md-newsletter",
        name: "Start a Newsletter",
        description: "Build email list of readers",
        effort: "medium",
        impact: "high",
        timeToResult: "8-12 weeks",
      },
    ],
  },

  threads: {
    name: "threads",
    displayName: "Threads",
    icon: "🧵",
    color: "#000000",
    bioMaxLength: 150,
    headlineMaxLength: 0,
    linkAllowed: false,
    linkLimit: 0,
    bestPostingTimes: ["9:00 AM", "1:00 PM", "7:00 PM"],
    contentTypes: ["Text Posts", "Images", "Videos", "Voice Notes"],
    audienceType: "Instagram users, early adopters, 18-40 age group",
    toneRecommendation: "Casual, conversational, authentic",
    monetizationOptions: [
      {
        id: "th-cross-promo",
        name: "Cross-Promote Instagram",
        description: "Drive traffic to monetized Instagram",
        eligibility: "Instagram account",
        earningPotential: "Varies",
        difficulty: "easy",
        timeToRevenue: "1-3 months",
      },
      {
        id: "th-brand-deals",
        name: "Brand Partnerships",
        description: "Sponsored threads (emerging)",
        eligibility: "10K+ followers",
        earningPotential: "$200-$10,000/post",
        difficulty: "medium",
        timeToRevenue: "3-6 months",
      },
      {
        id: "th-affiliate",
        name: "Affiliate Links",
        description: "Share affiliate links (via bio)",
        eligibility: "Any follower count",
        earningPotential: "$100-$5,000/month",
        difficulty: "easy",
        timeToRevenue: "2-4 months",
      },
      {
        id: "th-coaching",
        name: "Coaching Services",
        description: "Offer coaching through Threads",
        eligibility: "Expertise in niche",
        earningPotential: "$500-$10,000/month",
        difficulty: "medium",
        timeToRevenue: "3-6 months",
      },
      {
        id: "th-products",
        name: "Product Promotion",
        description: "Promote your products/services",
        eligibility: "Have products",
        earningPotential: "Varies",
        difficulty: "easy",
        timeToRevenue: "1-3 months",
      },
    ],
    growthStrategies: [
      {
        id: "th-consistency",
        name: "Post 5-10x Daily",
        description: "Threads favors active accounts",
        effort: "high",
        impact: "high",
        timeToResult: "4-8 weeks",
      },
      {
        id: "th-engagement",
        name: "Reply to Big Accounts",
        description: "Early replies get visibility",
        effort: "low",
        impact: "high",
        timeToResult: "2-4 weeks",
      },
      {
        id: "th-conversations",
        name: "Start Conversations",
        description: "Questions and polls drive engagement",
        effort: "low",
        impact: "medium",
        timeToResult: "2-4 weeks",
      },
      {
        id: "th-cross-post",
        name: "Cross-Post from Twitter",
        description: "Repurpose Twitter content",
        effort: "low",
        impact: "medium",
        timeToResult: "1-2 weeks",
      },
      {
        id: "th-niche",
        name: "Own a Conversation Topic",
        description: "Become known for specific topics",
        effort: "medium",
        impact: "high",
        timeToResult: "8-12 weeks",
      },
    ],
  },
};

export function getPlatformSpec(platform: string): PlatformSpec {
  return PLATFORM_SPECS[platform] || PLATFORM_SPECS.instagram;
}

export function getAllPlatforms(): PlatformSpec[] {
  return Object.values(PLATFORM_SPECS);
}

export function getMonetizationOptions(platform: string): MonetizationOption[] {
  return PLATFORM_SPECS[platform]?.monetizationOptions || [];
}

export function getGrowthStrategies(platform: string): GrowthStrategy[] {
  return PLATFORM_SPECS[platform]?.growthStrategies || [];
}