// app/dashboard/competitors/lib/mockCompetitors.ts
import { Competitor } from "@/types/competitor";

export const mockCompetitors: Competitor[] = [
  {
    id: "1",
    name: "Career Coach AI",
    handle: "@careercoachai",
    platform: "LinkedIn",
    niche: "AI Career Tools",
    website: "https://careercoachai.com",
    metrics: {
      followers: 125000,
      engagementRate: 4.8,
      avgPostsPerWeek: 5.2,
      growthRate: 12.5,
      totalLikes: 45000,
      totalComments: 3200,
    },
    growthTrend: [4.2, 4.5, 4.3, 4.8, 5.1, 4.9, 4.8],
    recentPosts: [
      {
        id: "p1",
        caption: "5 AI tools that wrote my resume for me...",
        publishedDate: "2024-04-14",
        likes: 1200,
        comments: 85,
        shares: 45,
        url: "#",
        type: "carousel",
      },
    ],
    lastUpdated: new Date().toISOString(),
    tags: ["AI", "Resume", "Tech"],
  },
  {
    id: "2",
    name: "Resume Genius",
    handle: "@resumegenius",
    platform: "Instagram",
    niche: "Resume Templates",
    website: "https://resumegenius.com",
    metrics: {
      followers: 89000,
      engagementRate: 3.2,
      avgPostsPerWeek: 3.5,
      growthRate: 5.8,
      totalLikes: 28000,
      totalComments: 1500,
    },
    growthTrend: [3.0, 3.1, 3.0, 3.2, 3.3, 3.2, 3.2],
    recentPosts: [],
    lastUpdated: new Date().toISOString(),
    tags: ["Templates", "Design"],
  },
  {
    id: "3",
    name: "LinkedIn Learning",
    handle: "@linkedinlearning",
    platform: "LinkedIn",
    niche: "Education",
    website: "https://linkedin.com/learning",
    metrics: {
      followers: 2500000,
      engagementRate: 2.1,
      avgPostsPerWeek: 7.0,
      growthRate: 8.4,
      totalLikes: 150000,
      totalComments: 12000,
    },
    growthTrend: [2.0, 2.1, 2.1, 2.2, 2.1, 2.1, 2.1],
    recentPosts: [],
    lastUpdated: new Date().toISOString(),
    tags: ["Education", "Courses"],
  },
  {
    id: "4",
    name: "The Career Expert",
    handle: "@thecareerexpert",
    platform: "TikTok",
    niche: "Interview Prep",
    website: "",
    metrics: {
      followers: 450000,
      engagementRate: 8.5,
      avgPostsPerWeek: 10.5,
      growthRate: 22.3,
      totalLikes: 890000,
      totalComments: 45000,
    },
    growthTrend: [7.5, 7.8, 8.0, 8.2, 8.5, 8.4, 8.5],
    recentPosts: [],
    lastUpdated: new Date().toISOString(),
    tags: ["Interview", "Video"],
  },
];

export const NICHE_OPTIONS = [
  "Resume Tips",
  "Interview Prep",
  "Salary Negotiation",
  "Career Coaching",
  "AI Career Tools",
  "Networking",
  "LinkedIn Optimization",
  "Job Search Strategy",
];