// app/dashboard/posts/lib/mockPosts.ts
import { Post } from "@/types/post";

export const mockPosts: Post[] = [
  {
    id: "1",
    caption: "🚀 Stop sending generic resumes! Here's how to tailor your application in 3 steps:\n\n1️⃣ Analyze the job description for keywords\n2️⃣ Mirror their language in your experience bullets\n3️⃣ Quantify your impact with metrics they care about\n\nYour dream job is waiting. Make them notice you. ✨\n\n#CareerTips #JobSearch #ResumeHelp",
    platforms: ["LinkedIn", "Instagram", "Twitter"],
    type: "carousel",
    status: "scheduled",
    scheduledDate: new Date("2024-04-15T14:00:00"),
    mediaUrl: "https://example.com/resume-tips-carousel.jpg",
    tags: ["resume", "job-search", "tips"],
    createdAt: new Date("2024-04-10T09:00:00"),
    updatedAt: new Date("2024-04-12T16:30:00"),
  },
  {
    id: "2",
    caption: "✨ Success Story: Maria went from 0 interviews to 5 offers in 30 days.\n\nHer secret? Our AI-powered resume optimizer + structured outreach system.\n\n🎯 Result: $25K salary increase\n🎯 Result: Remote role at top tech company\n🎯 Result: Confidence in negotiations\n\nYour transformation starts today. Link in bio 🔗",
    platforms: ["Instagram", "Facebook", "TikTok"],
    type: "video",
    status: "published",
    publishedDate: new Date("2024-04-08T10:00:00"),
    mediaUrl: "https://example.com/maria-success.mp4",
    tags: ["success-story", "testimonial", "results"],
    createdAt: new Date("2024-04-05T11:00:00"),
    updatedAt: new Date("2024-04-08T10:05:00"),
  },
  {
    id: "3",
    caption: "🤖 This AI tool just changed my cover letter game forever.\n\nI tested [Tool Name] for personalized outreach:\n\n📊 Before: 2% response rate\n📈 After: 34% response rate\n\nWhy it works:\n• Analyzes company culture from their website\n• Suggests tone-matched opening lines\n• Flags generic phrases recruiters skip\n\nTry it free → chasemycareer.com/tools",
    platforms: ["Twitter", "LinkedIn", "Medium"],
    type: "text",
    status: "draft",
    tags: ["ai-tools", "cover-letter", "productivity"],
    createdAt: new Date("2024-04-13T14:20:00"),
    updatedAt: new Date("2024-04-13T14:20:00"),
  },
  {
    id: "4",
    caption: "⏱️ 60-second career upgrade:\n\nChange this:\n❌ \"Responsible for managing social media\"\n\nTo this:\n✅ \"Grew Instagram following 340% (12K→53K) in 6 months through data-driven content strategy\"\n\nSmall tweak. Massive difference in how recruiters see you.\n\nWhat will you update today? 💬",
    platforms: ["Twitter", "Instagram", "LinkedIn"],
    type: "image",
    status: "backlog",
    mediaUrl: "https://example.com/before-after-resume.png",
    tags: ["quick-win", "resume-tips", "linkedin"],
    createdAt: new Date("2024-04-11T08:15:00"),
    updatedAt: new Date("2024-04-11T08:15:00"),
  },
  {
    id: "5",
    caption: "📊 LinkedIn hiring trend alert: Skills-based hiring is up 47% in 2024.\n\nWhat this means for you:\n🔹 Lead with certifications & projects, not just job titles\n🔹 Add a 'Skills' section above your experience\n🔹 Use LinkedIn's skill assessments (they're free!)\n🔹 Showcase micro-credentials from Coursera, Google, etc.\n\nStay ahead. Get hired faster.\n\n🔗 Full report: chasemycareer.com/trends",
    platforms: ["LinkedIn", "Website Blog", "Medium"],
    type: "diagram",
    status: "scheduled",
    scheduledDate: new Date("2024-04-18T09:00:00"),
    mediaUrl: "https://example.com/hiring-trends-2024.png",
    tags: ["industry-insight", "linkedin", "hiring-trends"],
    createdAt: new Date("2024-04-12T13:45:00"),
    updatedAt: new Date("2024-04-13T10:20:00"),
  },
];